modLoader="javafml"
loaderVersion="[4,)"
license="GPLv3"

[[mods]]
modId="neoauth"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[mixins]]
config="neoauth-neoforge.mixins.json"

[[dependencies.neoauth]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="SERVER"

[[dependencies.neoauth]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="SERVER"
