modLoader="javafml"
loaderVersion="[4,)"
license="GPLv3"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[mixins]]
config="neoauth-neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="tab"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="SERVER"

