modLoader="javafml"
loaderVersion="[47,)"
license="GPLv3"

[[mods]]
modId="neoauth"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[mixins]]
config="neoauth-forge.mixins.json"

[[dependencies.neoauth]]
modId="forge"
mandatory=true
versionRange="[47.3.0,)"
ordering="NONE"
side="SERVER"

[[dependencies.neoauth]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="SERVER"
