plugins {
    id 'java-library'
}

base {
    archivesName = 'neoauth-core'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

dependencies {
    // MariaDB JDBC 驅動
    api "org.mariadb.jdbc:mariadb-java-client:${mariadb_client_version}"

    // SQLite JDBC 驅動
    api "org.xerial:sqlite-jdbc:${sqlite_jdbc_version}"

    // HikariCP 高效連線池
    api "com.zaxxer:HikariCP:${hikaricp_version}"

    // BCrypt 密碼雜湊函式庫
    api "at.favre.lib:bcrypt:${bcrypt_version}"

    // SnakeYAML 解析函式庫
    api "org.yaml:snakeyaml:${snakeyaml_version}"

    // GSON JSON 解析函式庫
    api 'com.google.code.gson:gson:2.10.1'

    // SLF4J 日誌介面
    compileOnly "org.slf4j:slf4j-api:${slf4j_version}"

    // 單元測試
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

def replaceProperties = [
    mod_version: mod_version
]

tasks.named('processResources', ProcessResources).configure {
    inputs.properties replaceProperties
    filesMatching(['neoauth-version.properties']) {
        expand replaceProperties
    }
}
